// Types
import type { RateMeals } from '../../types/expenses';

export const INTL_MIE_RATES: RateMeals[] = [
    {
        total: 1,
        breakfast: 0,
        lunch: 0,
        dinner: 0,
        incidental: 1,
        FirstLastDay: 0.75,
    },
    {
        total: 2,
        breakfast: 0,
        lunch: 0,
        dinner: 1,
        incidental: 1,
        FirstLastDay: 1.5,
    },
    {
        total: 3,
        breakfast: 0,
        lunch: 1,
        dinner: 1,
        incidental: 1,
        FirstLastDay: 2.25,
    },
    {
        total: 4,
        breakfast: 1,
        lunch: 1,
        dinner: 1,
        incidental: 1,
        FirstLastDay: 3,
    },
    {
        total: 5,
        breakfast: 1,
        lunch: 1,
        dinner: 2,
        incidental: 1,
        FirstLastDay: 3.75,
    },
    {
        total: 6,
        breakfast: 1,
        lunch: 2,
        dinner: 2,
        incidental: 1,
        FirstLastDay: 4.5,
    },
    {
        total: 7,
        breakfast: 1,
        lunch: 2,
        dinner: 3,
        incidental: 1,
        FirstLastDay: 5.25,
    },
    {
        total: 8,
        breakfast: 1,
        lunch: 2,
        dinner: 3,
        incidental: 2,
        FirstLastDay: 6,
    },
    {
        total: 9,
        breakfast: 1,
        lunch: 2,
        dinner: 4,
        incidental: 2,
        FirstLastDay: 6.75,
    },
    {
        total: 10,
        breakfast: 2,
        lunch: 2,
        dinner: 4,
        incidental: 2,
        FirstLastDay: 7.5,
    },
    {
        total: 11,
        breakfast: 2,
        lunch: 3,
        dinner: 4,
        incidental: 2,
        FirstLastDay: 8.25,
    },
    {
        total: 12,
        breakfast: 2,
        lunch: 3,
        dinner: 5,
        incidental: 2,
        FirstLastDay: 9,
    },
    {
        total: 13,
        breakfast: 2,
        lunch: 3,
        dinner: 5,
        incidental: 3,
        FirstLastDay: 9.75,
    },
    {
        total: 14,
        breakfast: 2,
        lunch: 4,
        dinner: 5,
        incidental: 3,
        FirstLastDay: 10.5,
    },
    {
        total: 15,
        breakfast: 2,
        lunch: 4,
        dinner: 6,
        incidental: 3,
        FirstLastDay: 11.25,
    },
    {
        total: 16,
        breakfast: 2,
        lunch: 4,
        dinner: 7,
        incidental: 3,
        FirstLastDay: 12,
    },
    {
        total: 17,
        breakfast: 3,
        lunch: 4,
        dinner: 7,
        incidental: 3,
        FirstLastDay: 12.75,
    },
    {
        total: 18,
        breakfast: 3,
        lunch: 5,
        dinner: 7,
        incidental: 3,
        FirstLastDay: 13.5,
    },
    {
        total: 19,
        breakfast: 3,
        lunch: 5,
        dinner: 8,
        incidental: 3,
        FirstLastDay: 14.25,
    },
    {
        total: 20,
        breakfast: 3,
        lunch: 5,
        dinner: 8,
        incidental: 4,
        FirstLastDay: 15,
    },
    {
        total: 21,
        breakfast: 3,
        lunch: 5,
        dinner: 9,
        incidental: 4,
        FirstLastDay: 15.75,
    },
    {
        total: 22,
        breakfast: 3,
        lunch: 6,
        dinner: 9,
        incidental: 4,
        FirstLastDay: 16.5,
    },
    {
        total: 23,
        breakfast: 3,
        lunch: 6,
        dinner: 9,
        incidental: 5,
        FirstLastDay: 17.25,
    },
    {
        total: 24,
        breakfast: 4,
        lunch: 6,
        dinner: 9,
        incidental: 5,
        FirstLastDay: 18,
    },
    {
        total: 25,
        breakfast: 4,
        lunch: 6,
        dinner: 10,
        incidental: 5,
        FirstLastDay: 18.75,
    },
    {
        total: 26,
        breakfast: 4,
        lunch: 7,
        dinner: 11,
        incidental: 5,
        FirstLastDay: 19.5,
    },
    {
        total: 27,
        breakfast: 4,
        lunch: 7,
        dinner: 11,
        incidental: 5,
        FirstLastDay: 20.25,
    },
    {
        total: 28,
        breakfast: 4,
        lunch: 7,
        dinner: 11,
        incidental: 6,
        FirstLastDay: 21,
    },
    {
        total: 29,
        breakfast: 4,
        lunch: 7,
        dinner: 12,
        incidental: 6,
        FirstLastDay: 21.75,
    },
    {
        total: 30,
        breakfast: 5,
        lunch: 7,
        dinner: 12,
        incidental: 6,
        FirstLastDay: 22.5,
    },
    {
        total: 31,
        breakfast: 5,
        lunch: 8,
        dinner: 12,
        incidental: 6,
        FirstLastDay: 23.25,
    },
    {
        total: 32,
        breakfast: 5,
        lunch: 8,
        dinner: 13,
        incidental: 6,
        FirstLastDay: 24,
    },
    {
        total: 33,
        breakfast: 5,
        lunch: 8,
        dinner: 13,
        incidental: 7,
        FirstLastDay: 24.75,
    },
    {
        total: 34,
        breakfast: 5,
        lunch: 9,
        dinner: 13,
        incidental: 7,
        FirstLastDay: 25.5,
    },
    {
        total: 35,
        breakfast: 5,
        lunch: 9,
        dinner: 14,
        incidental: 7,
        FirstLastDay: 26.25,
    },
    {
        total: 36,
        breakfast: 5,
        lunch: 9,
        dinner: 15,
        incidental: 7,
        FirstLastDay: 27,
    },
    {
        total: 37,
        breakfast: 6,
        lunch: 9,
        dinner: 15,
        incidental: 7,
        FirstLastDay: 27.75,
    },
    {
        total: 38,
        breakfast: 6,
        lunch: 10,
        dinner: 15,
        incidental: 7,
        FirstLastDay: 28.5,
    },
    {
        total: 39,
        breakfast: 6,
        lunch: 10,
        dinner: 16,
        incidental: 7,
        FirstLastDay: 29.25,
    },
    {
        total: 40,
        breakfast: 6,
        lunch: 10,
        dinner: 16,
        incidental: 8,
        FirstLastDay: 30,
    },
    {
        total: 41,
        breakfast: 6,
        lunch: 10,
        dinner: 17,
        incidental: 8,
        FirstLastDay: 30.75,
    },
    {
        total: 42,
        breakfast: 6,
        lunch: 11,
        dinner: 17,
        incidental: 8,
        FirstLastDay: 31.5,
    },
    {
        total: 43,
        breakfast: 6,
        lunch: 11,
        dinner: 17,
        incidental: 9,
        FirstLastDay: 32.25,
    },
    {
        total: 44,
        breakfast: 7,
        lunch: 11,
        dinner: 17,
        incidental: 9,
        FirstLastDay: 33,
    },
    {
        total: 45,
        breakfast: 7,
        lunch: 11,
        dinner: 18,
        incidental: 9,
        FirstLastDay: 33.75,
    },
    {
        total: 46,
        breakfast: 7,
        lunch: 12,
        dinner: 18,
        incidental: 9,
        FirstLastDay: 34.5,
    },
    {
        total: 47,
        breakfast: 7,
        lunch: 12,
        dinner: 19,
        incidental: 9,
        FirstLastDay: 35.25,
    },
    {
        total: 48,
        breakfast: 7,
        lunch: 12,
        dinner: 19,
        incidental: 10,
        FirstLastDay: 36,
    },
    {
        total: 49,
        breakfast: 7,
        lunch: 12,
        dinner: 20,
        incidental: 10,
        FirstLastDay: 36.75,
    },
    {
        total: 50,
        breakfast: 8,
        lunch: 12,
        dinner: 20,
        incidental: 10,
        FirstLastDay: 37.5,
    },
    {
        total: 51,
        breakfast: 8,
        lunch: 13,
        dinner: 20,
        incidental: 10,
        FirstLastDay: 38.25,
    },
    {
        total: 52,
        breakfast: 8,
        lunch: 13,
        dinner: 21,
        incidental: 10,
        FirstLastDay: 39,
    },
    {
        total: 53,
        breakfast: 8,
        lunch: 13,
        dinner: 21,
        incidental: 11,
        FirstLastDay: 39.75,
    },
    {
        total: 54,
        breakfast: 8,
        lunch: 14,
        dinner: 21,
        incidental: 11,
        FirstLastDay: 40.5,
    },
    {
        total: 55,
        breakfast: 8,
        lunch: 14,
        dinner: 22,
        incidental: 11,
        FirstLastDay: 41.25,
    },
    {
        total: 56,
        breakfast: 8,
        lunch: 14,
        dinner: 23,
        incidental: 11,
        FirstLastDay: 42,
    },
    {
        total: 57,
        breakfast: 9,
        lunch: 14,
        dinner: 23,
        incidental: 11,
        FirstLastDay: 42.75,
    },
    {
        total: 58,
        breakfast: 9,
        lunch: 15,
        dinner: 23,
        incidental: 11,
        FirstLastDay: 43.5,
    },
    {
        total: 59,
        breakfast: 9,
        lunch: 15,
        dinner: 24,
        incidental: 11,
        FirstLastDay: 44.25,
    },
    {
        total: 60,
        breakfast: 9,
        lunch: 15,
        dinner: 24,
        incidental: 12,
        FirstLastDay: 45,
    },
    {
        total: 61,
        breakfast: 9,
        lunch: 15,
        dinner: 25,
        incidental: 12,
        FirstLastDay: 45.75,
    },
    {
        total: 62,
        breakfast: 9,
        lunch: 16,
        dinner: 25,
        incidental: 12,
        FirstLastDay: 46.5,
    },
    {
        total: 63,
        breakfast: 9,
        lunch: 16,
        dinner: 25,
        incidental: 13,
        FirstLastDay: 47.25,
    },
    {
        total: 64,
        breakfast: 10,
        lunch: 16,
        dinner: 25,
        incidental: 13,
        FirstLastDay: 48,
    },
    {
        total: 65,
        breakfast: 10,
        lunch: 16,
        dinner: 26,
        incidental: 13,
        FirstLastDay: 48.75,
    },
    {
        total: 66,
        breakfast: 10,
        lunch: 17,
        dinner: 26,
        incidental: 13,
        FirstLastDay: 49.5,
    },
    {
        total: 67,
        breakfast: 10,
        lunch: 17,
        dinner: 27,
        incidental: 13,
        FirstLastDay: 50.25,
    },
    {
        total: 68,
        breakfast: 10,
        lunch: 17,
        dinner: 27,
        incidental: 14,
        FirstLastDay: 51,
    },
    {
        total: 69,
        breakfast: 10,
        lunch: 17,
        dinner: 28,
        incidental: 14,
        FirstLastDay: 51.75,
    },
    {
        total: 70,
        breakfast: 11,
        lunch: 17,
        dinner: 28,
        incidental: 14,
        FirstLastDay: 52.5,
    },
    {
        total: 71,
        breakfast: 11,
        lunch: 18,
        dinner: 28,
        incidental: 14,
        FirstLastDay: 53.25,
    },
    {
        total: 72,
        breakfast: 11,
        lunch: 18,
        dinner: 29,
        incidental: 14,
        FirstLastDay: 54,
    },
    {
        total: 73,
        breakfast: 11,
        lunch: 18,
        dinner: 29,
        incidental: 15,
        FirstLastDay: 54.75,
    },
    {
        total: 74,
        breakfast: 11,
        lunch: 19,
        dinner: 29,
        incidental: 15,
        FirstLastDay: 55.5,
    },
    {
        total: 75,
        breakfast: 11,
        lunch: 19,
        dinner: 30,
        incidental: 15,
        FirstLastDay: 56.25,
    },
    {
        total: 76,
        breakfast: 11,
        lunch: 19,
        dinner: 31,
        incidental: 15,
        FirstLastDay: 57,
    },
    {
        total: 77,
        breakfast: 12,
        lunch: 19,
        dinner: 31,
        incidental: 15,
        FirstLastDay: 57.75,
    },
    {
        total: 78,
        breakfast: 12,
        lunch: 20,
        dinner: 31,
        incidental: 15,
        FirstLastDay: 58.5,
    },
    {
        total: 79,
        breakfast: 12,
        lunch: 20,
        dinner: 32,
        incidental: 15,
        FirstLastDay: 59.25,
    },
    {
        total: 80,
        breakfast: 12,
        lunch: 20,
        dinner: 32,
        incidental: 16,
        FirstLastDay: 60,
    },
    {
        total: 81,
        breakfast: 12,
        lunch: 20,
        dinner: 33,
        incidental: 16,
        FirstLastDay: 60.75,
    },
    {
        total: 82,
        breakfast: 12,
        lunch: 21,
        dinner: 33,
        incidental: 16,
        FirstLastDay: 61.5,
    },
    {
        total: 83,
        breakfast: 12,
        lunch: 21,
        dinner: 33,
        incidental: 17,
        FirstLastDay: 62.25,
    },
    {
        total: 84,
        breakfast: 13,
        lunch: 21,
        dinner: 33,
        incidental: 17,
        FirstLastDay: 63,
    },
    {
        total: 85,
        breakfast: 13,
        lunch: 21,
        dinner: 34,
        incidental: 17,
        FirstLastDay: 63.75,
    },
    {
        total: 86,
        breakfast: 13,
        lunch: 22,
        dinner: 34,
        incidental: 17,
        FirstLastDay: 64.5,
    },
    {
        total: 87,
        breakfast: 13,
        lunch: 22,
        dinner: 35,
        incidental: 17,
        FirstLastDay: 65.25,
    },
    {
        total: 88,
        breakfast: 13,
        lunch: 22,
        dinner: 35,
        incidental: 18,
        FirstLastDay: 66,
    },
    {
        total: 89,
        breakfast: 13,
        lunch: 22,
        dinner: 36,
        incidental: 18,
        FirstLastDay: 66.75,
    },
    {
        total: 90,
        breakfast: 14,
        lunch: 22,
        dinner: 36,
        incidental: 18,
        FirstLastDay: 67.5,
    },
    {
        total: 91,
        breakfast: 14,
        lunch: 23,
        dinner: 36,
        incidental: 18,
        FirstLastDay: 68.25,
    },
    {
        total: 92,
        breakfast: 14,
        lunch: 23,
        dinner: 37,
        incidental: 18,
        FirstLastDay: 69,
    },
    {
        total: 93,
        breakfast: 14,
        lunch: 23,
        dinner: 37,
        incidental: 19,
        FirstLastDay: 69.75,
    },
    {
        total: 94,
        breakfast: 14,
        lunch: 24,
        dinner: 37,
        incidental: 19,
        FirstLastDay: 70.5,
    },
    {
        total: 95,
        breakfast: 14,
        lunch: 24,
        dinner: 38,
        incidental: 19,
        FirstLastDay: 71.25,
    },
    {
        total: 96,
        breakfast: 14,
        lunch: 24,
        dinner: 39,
        incidental: 19,
        FirstLastDay: 72,
    },
    {
        total: 97,
        breakfast: 15,
        lunch: 24,
        dinner: 39,
        incidental: 19,
        FirstLastDay: 72.75,
    },
    {
        total: 98,
        breakfast: 15,
        lunch: 25,
        dinner: 39,
        incidental: 19,
        FirstLastDay: 73.5,
    },
    {
        total: 99,
        breakfast: 15,
        lunch: 25,
        dinner: 40,
        incidental: 19,
        FirstLastDay: 74.25,
    },
    {
        total: 100,
        breakfast: 15,
        lunch: 25,
        dinner: 40,
        incidental: 20,
        FirstLastDay: 75,
    },
    {
        total: 101,
        breakfast: 15,
        lunch: 25,
        dinner: 41,
        incidental: 20,
        FirstLastDay: 75.75,
    },
    {
        total: 102,
        breakfast: 15,
        lunch: 26,
        dinner: 41,
        incidental: 20,
        FirstLastDay: 76.5,
    },
    {
        total: 103,
        breakfast: 15,
        lunch: 26,
        dinner: 41,
        incidental: 21,
        FirstLastDay: 77.25,
    },
    {
        total: 104,
        breakfast: 16,
        lunch: 26,
        dinner: 41,
        incidental: 21,
        FirstLastDay: 78,
    },
    {
        total: 105,
        breakfast: 16,
        lunch: 26,
        dinner: 42,
        incidental: 21,
        FirstLastDay: 78.75,
    },
    {
        total: 106,
        breakfast: 16,
        lunch: 27,
        dinner: 42,
        incidental: 21,
        FirstLastDay: 79.5,
    },
    {
        total: 107,
        breakfast: 16,
        lunch: 27,
        dinner: 43,
        incidental: 21,
        FirstLastDay: 80.25,
    },
    {
        total: 108,
        breakfast: 16,
        lunch: 27,
        dinner: 43,
        incidental: 22,
        FirstLastDay: 81,
    },
    {
        total: 109,
        breakfast: 16,
        lunch: 27,
        dinner: 44,
        incidental: 22,
        FirstLastDay: 81.75,
    },
    {
        total: 110,
        breakfast: 17,
        lunch: 27,
        dinner: 44,
        incidental: 22,
        FirstLastDay: 82.5,
    },
    {
        total: 111,
        breakfast: 17,
        lunch: 28,
        dinner: 44,
        incidental: 22,
        FirstLastDay: 83.25,
    },
    {
        total: 112,
        breakfast: 17,
        lunch: 28,
        dinner: 45,
        incidental: 22,
        FirstLastDay: 84,
    },
    {
        total: 113,
        breakfast: 17,
        lunch: 28,
        dinner: 45,
        incidental: 23,
        FirstLastDay: 84.75,
    },
    {
        total: 114,
        breakfast: 17,
        lunch: 29,
        dinner: 45,
        incidental: 23,
        FirstLastDay: 85.5,
    },
    {
        total: 115,
        breakfast: 17,
        lunch: 29,
        dinner: 46,
        incidental: 23,
        FirstLastDay: 86.25,
    },
    {
        total: 116,
        breakfast: 17,
        lunch: 29,
        dinner: 47,
        incidental: 23,
        FirstLastDay: 87,
    },
    {
        total: 117,
        breakfast: 18,
        lunch: 29,
        dinner: 47,
        incidental: 23,
        FirstLastDay: 87.75,
    },
    {
        total: 118,
        breakfast: 18,
        lunch: 30,
        dinner: 47,
        incidental: 23,
        FirstLastDay: 88.5,
    },
    {
        total: 119,
        breakfast: 18,
        lunch: 30,
        dinner: 48,
        incidental: 23,
        FirstLastDay: 89.25,
    },
    {
        total: 120,
        breakfast: 18,
        lunch: 30,
        dinner: 48,
        incidental: 24,
        FirstLastDay: 90,
    },
    {
        total: 121,
        breakfast: 18,
        lunch: 30,
        dinner: 49,
        incidental: 24,
        FirstLastDay: 90.75,
    },
    {
        total: 122,
        breakfast: 18,
        lunch: 31,
        dinner: 49,
        incidental: 24,
        FirstLastDay: 91.5,
    },
    {
        total: 123,
        breakfast: 18,
        lunch: 31,
        dinner: 49,
        incidental: 25,
        FirstLastDay: 92.25,
    },
    {
        total: 124,
        breakfast: 19,
        lunch: 31,
        dinner: 49,
        incidental: 25,
        FirstLastDay: 93,
    },
    {
        total: 125,
        breakfast: 19,
        lunch: 31,
        dinner: 50,
        incidental: 25,
        FirstLastDay: 93.75,
    },
    {
        total: 126,
        breakfast: 19,
        lunch: 32,
        dinner: 50,
        incidental: 25,
        FirstLastDay: 94.5,
    },
    {
        total: 127,
        breakfast: 19,
        lunch: 32,
        dinner: 51,
        incidental: 25,
        FirstLastDay: 95.25,
    },
    {
        total: 128,
        breakfast: 19,
        lunch: 32,
        dinner: 51,
        incidental: 26,
        FirstLastDay: 96,
    },
    {
        total: 129,
        breakfast: 19,
        lunch: 32,
        dinner: 52,
        incidental: 26,
        FirstLastDay: 96.75,
    },
    {
        total: 130,
        breakfast: 20,
        lunch: 32,
        dinner: 52,
        incidental: 26,
        FirstLastDay: 97.5,
    },
    {
        total: 131,
        breakfast: 20,
        lunch: 33,
        dinner: 52,
        incidental: 26,
        FirstLastDay: 98.25,
    },
    {
        total: 132,
        breakfast: 20,
        lunch: 33,
        dinner: 53,
        incidental: 26,
        FirstLastDay: 99,
    },
    {
        total: 133,
        breakfast: 20,
        lunch: 33,
        dinner: 53,
        incidental: 27,
        FirstLastDay: 99.75,
    },
    {
        total: 134,
        breakfast: 20,
        lunch: 34,
        dinner: 53,
        incidental: 27,
        FirstLastDay: 100.5,
    },
    {
        total: 135,
        breakfast: 20,
        lunch: 34,
        dinner: 54,
        incidental: 27,
        FirstLastDay: 101.25,
    },
    {
        total: 136,
        breakfast: 20,
        lunch: 34,
        dinner: 55,
        incidental: 27,
        FirstLastDay: 102,
    },
    {
        total: 137,
        breakfast: 21,
        lunch: 34,
        dinner: 55,
        incidental: 27,
        FirstLastDay: 102.75,
    },
    {
        total: 138,
        breakfast: 21,
        lunch: 35,
        dinner: 55,
        incidental: 27,
        FirstLastDay: 103.5,
    },
    {
        total: 139,
        breakfast: 21,
        lunch: 35,
        dinner: 56,
        incidental: 27,
        FirstLastDay: 104.25,
    },
    {
        total: 140,
        breakfast: 21,
        lunch: 35,
        dinner: 56,
        incidental: 28,
        FirstLastDay: 105,
    },
    {
        total: 141,
        breakfast: 21,
        lunch: 35,
        dinner: 57,
        incidental: 28,
        FirstLastDay: 105.75,
    },
    {
        total: 142,
        breakfast: 21,
        lunch: 36,
        dinner: 57,
        incidental: 28,
        FirstLastDay: 106.5,
    },
    {
        total: 143,
        breakfast: 21,
        lunch: 36,
        dinner: 57,
        incidental: 29,
        FirstLastDay: 107.25,
    },
    {
        total: 144,
        breakfast: 22,
        lunch: 36,
        dinner: 57,
        incidental: 29,
        FirstLastDay: 108,
    },
    {
        total: 145,
        breakfast: 22,
        lunch: 36,
        dinner: 58,
        incidental: 29,
        FirstLastDay: 108.75,
    },
    {
        total: 146,
        breakfast: 22,
        lunch: 37,
        dinner: 58,
        incidental: 29,
        FirstLastDay: 109.5,
    },
    {
        total: 147,
        breakfast: 22,
        lunch: 37,
        dinner: 59,
        incidental: 29,
        FirstLastDay: 110.25,
    },
    {
        total: 148,
        breakfast: 22,
        lunch: 37,
        dinner: 59,
        incidental: 30,
        FirstLastDay: 111,
    },
    {
        total: 149,
        breakfast: 22,
        lunch: 37,
        dinner: 60,
        incidental: 30,
        FirstLastDay: 111.75,
    },
    {
        total: 150,
        breakfast: 23,
        lunch: 37,
        dinner: 60,
        incidental: 30,
        FirstLastDay: 112.5,
    },
    {
        total: 151,
        breakfast: 23,
        lunch: 38,
        dinner: 60,
        incidental: 30,
        FirstLastDay: 113.25,
    },
    {
        total: 152,
        breakfast: 23,
        lunch: 38,
        dinner: 61,
        incidental: 30,
        FirstLastDay: 114,
    },
    {
        total: 153,
        breakfast: 23,
        lunch: 38,
        dinner: 61,
        incidental: 31,
        FirstLastDay: 114.75,
    },
    {
        total: 154,
        breakfast: 23,
        lunch: 39,
        dinner: 61,
        incidental: 31,
        FirstLastDay: 115.5,
    },
    {
        total: 155,
        breakfast: 23,
        lunch: 39,
        dinner: 62,
        incidental: 31,
        FirstLastDay: 116.25,
    },
    {
        total: 156,
        breakfast: 23,
        lunch: 39,
        dinner: 63,
        incidental: 31,
        FirstLastDay: 117,
    },
    {
        total: 157,
        breakfast: 24,
        lunch: 39,
        dinner: 63,
        incidental: 31,
        FirstLastDay: 117.75,
    },
    {
        total: 158,
        breakfast: 24,
        lunch: 40,
        dinner: 63,
        incidental: 31,
        FirstLastDay: 118.5,
    },
    {
        total: 159,
        breakfast: 24,
        lunch: 40,
        dinner: 64,
        incidental: 31,
        FirstLastDay: 119.25,
    },
    {
        total: 160,
        breakfast: 24,
        lunch: 40,
        dinner: 64,
        incidental: 32,
        FirstLastDay: 120,
    },
    {
        total: 161,
        breakfast: 24,
        lunch: 40,
        dinner: 65,
        incidental: 32,
        FirstLastDay: 120.75,
    },
    {
        total: 162,
        breakfast: 24,
        lunch: 41,
        dinner: 65,
        incidental: 32,
        FirstLastDay: 121.5,
    },
    {
        total: 163,
        breakfast: 24,
        lunch: 41,
        dinner: 65,
        incidental: 33,
        FirstLastDay: 122.25,
    },
    {
        total: 164,
        breakfast: 25,
        lunch: 41,
        dinner: 65,
        incidental: 33,
        FirstLastDay: 123,
    },
    {
        total: 165,
        breakfast: 25,
        lunch: 41,
        dinner: 66,
        incidental: 33,
        FirstLastDay: 123.75,
    },
    {
        total: 166,
        breakfast: 25,
        lunch: 42,
        dinner: 66,
        incidental: 33,
        FirstLastDay: 124.5,
    },
    {
        total: 167,
        breakfast: 25,
        lunch: 42,
        dinner: 67,
        incidental: 33,
        FirstLastDay: 125.25,
    },
    {
        total: 168,
        breakfast: 25,
        lunch: 42,
        dinner: 67,
        incidental: 34,
        FirstLastDay: 126,
    },
    {
        total: 169,
        breakfast: 25,
        lunch: 42,
        dinner: 68,
        incidental: 34,
        FirstLastDay: 126.75,
    },
    {
        total: 170,
        breakfast: 26,
        lunch: 42,
        dinner: 68,
        incidental: 34,
        FirstLastDay: 127.5,
    },
    {
        total: 171,
        breakfast: 26,
        lunch: 43,
        dinner: 68,
        incidental: 34,
        FirstLastDay: 128.25,
    },
    {
        total: 172,
        breakfast: 26,
        lunch: 43,
        dinner: 69,
        incidental: 34,
        FirstLastDay: 129,
    },
    {
        total: 173,
        breakfast: 26,
        lunch: 43,
        dinner: 69,
        incidental: 35,
        FirstLastDay: 129.75,
    },
    {
        total: 174,
        breakfast: 26,
        lunch: 44,
        dinner: 69,
        incidental: 35,
        FirstLastDay: 130.5,
    },
    {
        total: 175,
        breakfast: 26,
        lunch: 44,
        dinner: 70,
        incidental: 35,
        FirstLastDay: 131.25,
    },
    {
        total: 176,
        breakfast: 26,
        lunch: 44,
        dinner: 71,
        incidental: 35,
        FirstLastDay: 132,
    },
    {
        total: 177,
        breakfast: 27,
        lunch: 44,
        dinner: 71,
        incidental: 35,
        FirstLastDay: 132.75,
    },
    {
        total: 178,
        breakfast: 27,
        lunch: 45,
        dinner: 71,
        incidental: 35,
        FirstLastDay: 133.5,
    },
    {
        total: 179,
        breakfast: 27,
        lunch: 45,
        dinner: 72,
        incidental: 35,
        FirstLastDay: 134.25,
    },
    {
        total: 180,
        breakfast: 27,
        lunch: 45,
        dinner: 72,
        incidental: 36,
        FirstLastDay: 135,
    },
    {
        total: 181,
        breakfast: 27,
        lunch: 45,
        dinner: 73,
        incidental: 36,
        FirstLastDay: 135.75,
    },
    {
        total: 182,
        breakfast: 27,
        lunch: 46,
        dinner: 73,
        incidental: 36,
        FirstLastDay: 136.5,
    },
    {
        total: 183,
        breakfast: 27,
        lunch: 46,
        dinner: 73,
        incidental: 37,
        FirstLastDay: 137.25,
    },
    {
        total: 184,
        breakfast: 28,
        lunch: 46,
        dinner: 73,
        incidental: 37,
        FirstLastDay: 138,
    },
    {
        total: 185,
        breakfast: 28,
        lunch: 46,
        dinner: 74,
        incidental: 37,
        FirstLastDay: 138.75,
    },
    {
        total: 186,
        breakfast: 28,
        lunch: 47,
        dinner: 74,
        incidental: 37,
        FirstLastDay: 139.5,
    },
    {
        total: 187,
        breakfast: 28,
        lunch: 47,
        dinner: 75,
        incidental: 37,
        FirstLastDay: 140.25,
    },
    {
        total: 188,
        breakfast: 28,
        lunch: 47,
        dinner: 75,
        incidental: 38,
        FirstLastDay: 141,
    },
    {
        total: 189,
        breakfast: 28,
        lunch: 47,
        dinner: 76,
        incidental: 38,
        FirstLastDay: 141.75,
    },
    {
        total: 190,
        breakfast: 29,
        lunch: 47,
        dinner: 76,
        incidental: 38,
        FirstLastDay: 142.5,
    },
    {
        total: 191,
        breakfast: 29,
        lunch: 48,
        dinner: 76,
        incidental: 38,
        FirstLastDay: 143.25,
    },
    {
        total: 192,
        breakfast: 29,
        lunch: 48,
        dinner: 77,
        incidental: 38,
        FirstLastDay: 144,
    },
    {
        total: 193,
        breakfast: 29,
        lunch: 48,
        dinner: 77,
        incidental: 39,
        FirstLastDay: 144.75,
    },
    {
        total: 194,
        breakfast: 29,
        lunch: 49,
        dinner: 77,
        incidental: 39,
        FirstLastDay: 145.5,
    },
    {
        total: 195,
        breakfast: 29,
        lunch: 49,
        dinner: 78,
        incidental: 39,
        FirstLastDay: 146.25,
    },
    {
        total: 196,
        breakfast: 29,
        lunch: 49,
        dinner: 79,
        incidental: 39,
        FirstLastDay: 147,
    },
    {
        total: 197,
        breakfast: 30,
        lunch: 49,
        dinner: 79,
        incidental: 39,
        FirstLastDay: 147.75,
    },
    {
        total: 198,
        breakfast: 30,
        lunch: 50,
        dinner: 79,
        incidental: 39,
        FirstLastDay: 148.5,
    },
    {
        total: 199,
        breakfast: 30,
        lunch: 50,
        dinner: 80,
        incidental: 39,
        FirstLastDay: 149.25,
    },
    {
        total: 200,
        breakfast: 30,
        lunch: 50,
        dinner: 80,
        incidental: 40,
        FirstLastDay: 150,
    },
    {
        total: 201,
        breakfast: 30,
        lunch: 50,
        dinner: 81,
        incidental: 40,
        FirstLastDay: 150.75,
    },
    {
        total: 202,
        breakfast: 30,
        lunch: 51,
        dinner: 81,
        incidental: 40,
        FirstLastDay: 151.5,
    },
    {
        total: 203,
        breakfast: 30,
        lunch: 51,
        dinner: 81,
        incidental: 41,
        FirstLastDay: 152.25,
    },
    {
        total: 204,
        breakfast: 31,
        lunch: 51,
        dinner: 81,
        incidental: 41,
        FirstLastDay: 153,
    },
    {
        total: 205,
        breakfast: 31,
        lunch: 51,
        dinner: 82,
        incidental: 41,
        FirstLastDay: 153.75,
    },
    {
        total: 206,
        breakfast: 31,
        lunch: 52,
        dinner: 82,
        incidental: 41,
        FirstLastDay: 154.5,
    },
    {
        total: 207,
        breakfast: 31,
        lunch: 52,
        dinner: 83,
        incidental: 41,
        FirstLastDay: 155.25,
    },
    {
        total: 208,
        breakfast: 31,
        lunch: 52,
        dinner: 83,
        incidental: 42,
        FirstLastDay: 156,
    },
    {
        total: 209,
        breakfast: 31,
        lunch: 52,
        dinner: 84,
        incidental: 42,
        FirstLastDay: 156.75,
    },
    {
        total: 210,
        breakfast: 32,
        lunch: 52,
        dinner: 84,
        incidental: 42,
        FirstLastDay: 157.5,
    },
    {
        total: 211,
        breakfast: 32,
        lunch: 53,
        dinner: 84,
        incidental: 42,
        FirstLastDay: 158.25,
    },
    {
        total: 212,
        breakfast: 32,
        lunch: 53,
        dinner: 85,
        incidental: 42,
        FirstLastDay: 159,
    },
    {
        total: 213,
        breakfast: 32,
        lunch: 53,
        dinner: 85,
        incidental: 43,
        FirstLastDay: 159.75,
    },
    {
        total: 214,
        breakfast: 32,
        lunch: 54,
        dinner: 85,
        incidental: 43,
        FirstLastDay: 160.5,
    },
    {
        total: 215,
        breakfast: 32,
        lunch: 54,
        dinner: 86,
        incidental: 43,
        FirstLastDay: 161.25,
    },
    {
        total: 216,
        breakfast: 32,
        lunch: 54,
        dinner: 87,
        incidental: 43,
        FirstLastDay: 162,
    },
    {
        total: 217,
        breakfast: 33,
        lunch: 54,
        dinner: 87,
        incidental: 43,
        FirstLastDay: 162.75,
    },
    {
        total: 218,
        breakfast: 33,
        lunch: 55,
        dinner: 87,
        incidental: 43,
        FirstLastDay: 163.5,
    },
    {
        total: 219,
        breakfast: 33,
        lunch: 55,
        dinner: 88,
        incidental: 43,
        FirstLastDay: 164.25,
    },
    {
        total: 220,
        breakfast: 33,
        lunch: 55,
        dinner: 88,
        incidental: 44,
        FirstLastDay: 165,
    },
    {
        total: 221,
        breakfast: 33,
        lunch: 55,
        dinner: 89,
        incidental: 44,
        FirstLastDay: 165.75,
    },
    {
        total: 222,
        breakfast: 33,
        lunch: 56,
        dinner: 89,
        incidental: 44,
        FirstLastDay: 166.5,
    },
    {
        total: 223,
        breakfast: 33,
        lunch: 56,
        dinner: 89,
        incidental: 45,
        FirstLastDay: 167.25,
    },
    {
        total: 224,
        breakfast: 34,
        lunch: 56,
        dinner: 89,
        incidental: 45,
        FirstLastDay: 168,
    },
    {
        total: 225,
        breakfast: 34,
        lunch: 56,
        dinner: 90,
        incidental: 45,
        FirstLastDay: 168.75,
    },
    {
        total: 226,
        breakfast: 34,
        lunch: 57,
        dinner: 90,
        incidental: 45,
        FirstLastDay: 169.5,
    },
    {
        total: 227,
        breakfast: 34,
        lunch: 57,
        dinner: 91,
        incidental: 45,
        FirstLastDay: 170.25,
    },
    {
        total: 228,
        breakfast: 34,
        lunch: 57,
        dinner: 91,
        incidental: 46,
        FirstLastDay: 171,
    },
    {
        total: 229,
        breakfast: 34,
        lunch: 57,
        dinner: 92,
        incidental: 46,
        FirstLastDay: 171.75,
    },
    {
        total: 230,
        breakfast: 35,
        lunch: 57,
        dinner: 92,
        incidental: 46,
        FirstLastDay: 172.5,
    },
    {
        total: 231,
        breakfast: 35,
        lunch: 58,
        dinner: 92,
        incidental: 46,
        FirstLastDay: 173.25,
    },
    {
        total: 232,
        breakfast: 35,
        lunch: 58,
        dinner: 93,
        incidental: 46,
        FirstLastDay: 174,
    },
    {
        total: 233,
        breakfast: 35,
        lunch: 58,
        dinner: 93,
        incidental: 47,
        FirstLastDay: 174.75,
    },
    {
        total: 234,
        breakfast: 35,
        lunch: 59,
        dinner: 93,
        incidental: 47,
        FirstLastDay: 175.5,
    },
    {
        total: 235,
        breakfast: 35,
        lunch: 59,
        dinner: 94,
        incidental: 47,
        FirstLastDay: 176.25,
    },
    {
        total: 236,
        breakfast: 35,
        lunch: 59,
        dinner: 95,
        incidental: 47,
        FirstLastDay: 177,
    },
    {
        total: 237,
        breakfast: 36,
        lunch: 59,
        dinner: 95,
        incidental: 47,
        FirstLastDay: 177.75,
    },
    {
        total: 238,
        breakfast: 36,
        lunch: 60,
        dinner: 95,
        incidental: 47,
        FirstLastDay: 178.5,
    },
    {
        total: 239,
        breakfast: 36,
        lunch: 60,
        dinner: 96,
        incidental: 47,
        FirstLastDay: 179.25,
    },
    {
        total: 240,
        breakfast: 36,
        lunch: 60,
        dinner: 96,
        incidental: 48,
        FirstLastDay: 180,
    },
    {
        total: 241,
        breakfast: 36,
        lunch: 60,
        dinner: 97,
        incidental: 48,
        FirstLastDay: 180.75,
    },
    {
        total: 242,
        breakfast: 36,
        lunch: 61,
        dinner: 97,
        incidental: 48,
        FirstLastDay: 181.5,
    },
    {
        total: 243,
        breakfast: 36,
        lunch: 61,
        dinner: 97,
        incidental: 49,
        FirstLastDay: 182.25,
    },
    {
        total: 244,
        breakfast: 37,
        lunch: 61,
        dinner: 97,
        incidental: 49,
        FirstLastDay: 183,
    },
    {
        total: 245,
        breakfast: 37,
        lunch: 61,
        dinner: 98,
        incidental: 49,
        FirstLastDay: 183.75,
    },
    {
        total: 246,
        breakfast: 37,
        lunch: 62,
        dinner: 98,
        incidental: 49,
        FirstLastDay: 184.5,
    },
    {
        total: 247,
        breakfast: 37,
        lunch: 62,
        dinner: 99,
        incidental: 49,
        FirstLastDay: 185.25,
    },
    {
        total: 248,
        breakfast: 37,
        lunch: 62,
        dinner: 99,
        incidental: 50,
        FirstLastDay: 186,
    },
    {
        total: 249,
        breakfast: 37,
        lunch: 62,
        dinner: 100,
        incidental: 50,
        FirstLastDay: 186.75,
    },
    {
        total: 250,
        breakfast: 38,
        lunch: 62,
        dinner: 100,
        incidental: 50,
        FirstLastDay: 187.5,
    },
    {
        total: 251,
        breakfast: 38,
        lunch: 63,
        dinner: 100,
        incidental: 50,
        FirstLastDay: 188.25,
    },
    {
        total: 252,
        breakfast: 38,
        lunch: 63,
        dinner: 101,
        incidental: 50,
        FirstLastDay: 189,
    },
    {
        total: 253,
        breakfast: 38,
        lunch: 63,
        dinner: 101,
        incidental: 51,
        FirstLastDay: 189.75,
    },
    {
        total: 254,
        breakfast: 38,
        lunch: 64,
        dinner: 101,
        incidental: 51,
        FirstLastDay: 190.5,
    },
    {
        total: 255,
        breakfast: 38,
        lunch: 64,
        dinner: 102,
        incidental: 51,
        FirstLastDay: 191.25,
    },
    {
        total: 256,
        breakfast: 38,
        lunch: 64,
        dinner: 103,
        incidental: 51,
        FirstLastDay: 192,
    },
    {
        total: 257,
        breakfast: 39,
        lunch: 64,
        dinner: 103,
        incidental: 51,
        FirstLastDay: 192.75,
    },
    {
        total: 258,
        breakfast: 39,
        lunch: 65,
        dinner: 103,
        incidental: 51,
        FirstLastDay: 193.5,
    },
    {
        total: 259,
        breakfast: 39,
        lunch: 65,
        dinner: 104,
        incidental: 51,
        FirstLastDay: 194.25,
    },
    {
        total: 260,
        breakfast: 39,
        lunch: 65,
        dinner: 104,
        incidental: 52,
        FirstLastDay: 195,
    },
    {
        total: 261,
        breakfast: 39,
        lunch: 65,
        dinner: 105,
        incidental: 52,
        FirstLastDay: 195.75,
    },
    {
        total: 262,
        breakfast: 39,
        lunch: 66,
        dinner: 105,
        incidental: 52,
        FirstLastDay: 196.5,
    },
    {
        total: 263,
        breakfast: 39,
        lunch: 66,
        dinner: 105,
        incidental: 53,
        FirstLastDay: 197.25,
    },
    {
        total: 264,
        breakfast: 40,
        lunch: 66,
        dinner: 105,
        incidental: 53,
        FirstLastDay: 198,
    },
    {
        total: 265,
        breakfast: 40,
        lunch: 66,
        dinner: 106,
        incidental: 53,
        FirstLastDay: 198.75,
    },
];
