// TEST Try different config options

import { Pdc } from './ts/controller';

const container = document.querySelector('#perDiemCalc');
if (!container)
    throw new Error('Failed to find container element for controller.');
const pdc = new Pdc(container, {
    expense: {
        headingPrint: `Per Diem Report`,
        bodyPrint: `Generated by <a href="https://perdiemcalc.org">https://perdiemcalc.org</a>`,
    },
});

pdc.addEventListener('expenseUpdate', ((e: CustomEvent) => {
    const { data } = e.detail;
    console.table(data);
}) as EventListener);
