// import { Pdc } from './ts/controller';

// const container = document.querySelector('#perDiemCalc') as HTMLElement;

// new Pdc(container, {
//     expense: {
//         headingPrint: `Per Diem Report`,
//         bodyPrint: `Generated by <a href="https://perdiemcalc.org">https://perdiemcalc.org</a>`,
//     },
// });

export { Pdc } from './ts/controller';
