export type LocationFromList = {
  name: string;
  abbreviation: string;
  label: string;
  category: string;
};

// Array of US States excluding OCON locations like Alaska, territories, etc.
export const ListStates: LocationFromList[] = [
  {
    name: 'Alabama',
    abbreviation: 'AL',
    label: 'Alabama (AL)',
    category: 'states',
  },
  {
    name: 'Arizona',
    abbreviation: 'AZ',
    label: 'Arizona (AZ)',
    category: 'states',
  },
  {
    name: 'Arkansas',
    abbreviation: 'AR',
    label: 'Arkansas (AR)',
    category: 'states',
  },
  {
    name: 'California',
    abbreviation: 'CA',
    label: 'California (CA)',
    category: 'states',
  },
  {
    name: 'Colorado',
    abbreviation: 'CO',
    label: 'Colorado (CO)',
    category: 'states',
  },
  {
    name: 'Connecticut',
    abbreviation: 'CT',
    label: 'Connecticut (CT)',
    category: 'states',
  },
  {
    name: 'Delaware',
    abbreviation: 'DE',
    label: 'Delaware (DE)',
    category: 'states',
  },
  {
    name: 'District Of Columbia',
    abbreviation: 'DC',
    label: 'District Of Columbia (DC)',
    category: 'states',
  },
  {
    name: 'Florida',
    abbreviation: 'FL',
    label: 'Florida (FL)',
    category: 'states',
  },
  {
    name: 'Georgia',
    abbreviation: 'GA',
    label: 'Georgia (GA)',
    category: 'states',
  },
  {
    name: 'Idaho',
    abbreviation: 'ID',
    label: 'Idaho (ID)',
    category: 'states',
  },
  {
    name: 'Illinois',
    abbreviation: 'IL',
    label: 'Illinois (IL)',
    category: 'states',
  },
  {
    name: 'Indiana',
    abbreviation: 'IN',
    label: 'Indiana (IN)',
    category: 'states',
  },
  {
    name: 'Iowa',
    abbreviation: 'IA',
    label: 'Iowa (IA)',
    category: 'states',
  },
  {
    name: 'Kansas',
    abbreviation: 'KS',
    label: 'Kansas (KS)',
    category: 'states',
  },
  {
    name: 'Kentucky',
    abbreviation: 'KY',
    label: 'Kentucky (KY)',
    category: 'states',
  },
  {
    name: 'Louisiana',
    abbreviation: 'LA',
    label: 'Louisiana (LA)',
    category: 'states',
  },
  {
    name: 'Maine',
    abbreviation: 'ME',
    label: 'Maine (ME)',
    category: 'states',
  },
  {
    name: 'Maryland',
    abbreviation: 'MD',
    label: 'Maryland (MD)',
    category: 'states',
  },
  {
    name: 'Massachusetts',
    abbreviation: 'MA',
    label: 'Massachusetts (MA)',
    category: 'states',
  },
  {
    name: 'Michigan',
    abbreviation: 'MI',
    label: 'Michigan (MI)',
    category: 'states',
  },
  {
    name: 'Minnesota',
    abbreviation: 'MN',
    label: 'Minnesota (MN)',
    category: 'states',
  },
  {
    name: 'Mississippi',
    abbreviation: 'MS',
    label: 'Mississippi (MS)',
    category: 'states',
  },
  {
    name: 'Missouri',
    abbreviation: 'MO',
    label: 'Missouri (MO)',
    category: 'states',
  },
  {
    name: 'Montana',
    abbreviation: 'MT',
    label: 'Montana (MT)',
    category: 'states',
  },
  {
    name: 'Nebraska',
    abbreviation: 'NE',
    label: 'Nebraska (NE)',
    category: 'states',
  },
  {
    name: 'Nevada',
    abbreviation: 'NV',
    label: 'Nevada (NV)',
    category: 'states',
  },
  {
    name: 'New Hampshire',
    abbreviation: 'NH',
    label: 'New Hampshire (NH)',
    category: 'states',
  },
  {
    name: 'New Jersey',
    abbreviation: 'NJ',
    label: 'New Jersey (NJ)',
    category: 'states',
  },
  {
    name: 'New Mexico',
    abbreviation: 'NM',
    label: 'New Mexico (NM)',
    category: 'states',
  },
  {
    name: 'New York',
    abbreviation: 'NY',
    label: 'New York (NY)',
    category: 'states',
  },
  {
    name: 'North Carolina',
    abbreviation: 'NC',
    label: 'North Carolina (NC)',
    category: 'states',
  },
  {
    name: 'North Dakota',
    abbreviation: 'ND',
    label: 'North Dakota (ND)',
    category: 'states',
  },
  {
    name: 'Ohio',
    abbreviation: 'OH',
    label: 'Ohio (OH)',
    category: 'states',
  },
  {
    name: 'Oklahoma',
    abbreviation: 'OK',
    label: 'Oklahoma (OK)',
    category: 'states',
  },
  {
    name: 'Oregon',
    abbreviation: 'OR',
    label: 'Oregon (OR)',
    category: 'states',
  },
  {
    name: 'Pennsylvania',
    abbreviation: 'PA',
    label: 'Pennsylvania (PA)',
    category: 'states',
  },
  {
    name: 'Rhode Island',
    abbreviation: 'RI',
    label: 'Rhode Island (RI)',
    category: 'states',
  },
  {
    name: 'South Carolina',
    abbreviation: 'SC',
    label: 'South Carolina (SC)',
    category: 'states',
  },
  {
    name: 'South Dakota',
    abbreviation: 'SD',
    label: 'South Dakota (SD)',
    category: 'states',
  },
  {
    name: 'Tennessee',
    abbreviation: 'TN',
    label: 'Tennessee (TN)',
    category: 'states',
  },
  {
    name: 'Texas',
    abbreviation: 'TX',
    label: 'Texas (TX)',
    category: 'states',
  },
  {
    name: 'Utah',
    abbreviation: 'UT',
    label: 'Utah (UT)',
    category: 'states',
  },
  {
    name: 'Vermont',
    abbreviation: 'VT',
    label: 'Vermont (VT)',
    category: 'states',
  },
  {
    name: 'Virginia',
    abbreviation: 'VA',
    label: 'Virginia (VA)',
    category: 'states',
  },
  {
    name: 'Washington',
    abbreviation: 'WA',
    label: 'Washington (WA)',
    category: 'states',
  },
  {
    name: 'West Virginia',
    abbreviation: 'WV',
    label: 'West Virginia (WV)',
    category: 'states',
  },
  {
    name: 'Wisconsin',
    abbreviation: 'WI',
    label: 'Wisconsin (WI)',
    category: 'states',
  },
  {
    name: 'Wyoming',
    abbreviation: 'WY',
    label: 'Wyoming (WY)',
    category: 'states',
  },
];

// Array of unique countries from OCONUSrates
export const ListCountries: LocationFromList[] = [
  {
    label: 'ARUBA (ABW)',
    category: 'countries',
    name: 'ARUBA',
    abbreviation: 'ABW',
  },
  {
    label: 'AFGHANISTAN (AFG)',
    category: 'countries',
    name: 'AFGHANISTAN',
    abbreviation: 'AFG',
  },
  {
    label: 'ANGOLA (AGO)',
    category: 'countries',
    name: 'ANGOLA',
    abbreviation: 'AGO',
  },
  {
    label: 'ANGUILLA (AIA)',
    category: 'countries',
    name: 'ANGUILLA',
    abbreviation: 'AIA',
  },
  {
    label: 'ALASKA (AK)',
    category: 'countries',
    name: 'ALASKA',
    abbreviation: 'AK',
  },
  {
    label: 'ALBANIA (ALB)',
    category: 'countries',
    name: 'ALBANIA',
    abbreviation: 'ALB',
  },
  {
    label: 'ALL PLACES NOT LISTED (ALL)',
    category: 'countries',
    name: 'ALL PLACES NOT LISTED',
    abbreviation: 'ALL',
  },
  {
    label: 'ANDORRA (AND)',
    category: 'countries',
    name: 'ANDORRA',
    abbreviation: 'AND',
  },
  {
    label: 'UNITED ARAB EMIRATES (ARE)',
    category: 'countries',
    name: 'UNITED ARAB EMIRATES',
    abbreviation: 'ARE',
  },
  {
    label: 'ARGENTINA (ARG)',
    category: 'countries',
    name: 'ARGENTINA',
    abbreviation: 'ARG',
  },
  {
    label: 'ARMENIA (ARM)',
    category: 'countries',
    name: 'ARMENIA',
    abbreviation: 'ARM',
  },
  {
    label: 'AMERICAN SAMOA (AS)',
    category: 'countries',
    name: 'AMERICAN SAMOA',
    abbreviation: 'AS',
  },
  {
    label: 'ASCENSION ISLAND (ASC)',
    category: 'countries',
    name: 'ASCENSION ISLAND',
    abbreviation: 'ASC',
  },
  {
    label: 'ANTARCTICA (ATA)',
    category: 'countries',
    name: 'ANTARCTICA',
    abbreviation: 'ATA',
  },
  {
    label: 'ANTIGUA AND BARBUDA (ATG)',
    category: 'countries',
    name: 'ANTIGUA AND BARBUDA',
    abbreviation: 'ATG',
  },
  {
    label: 'AUSTRALIA (AUS)',
    category: 'countries',
    name: 'AUSTRALIA',
    abbreviation: 'AUS',
  },
  {
    label: 'AUSTRIA (AUT)',
    category: 'countries',
    name: 'AUSTRIA',
    abbreviation: 'AUT',
  },
  {
    label: 'AZERBAIJAN (AZE)',
    category: 'countries',
    name: 'AZERBAIJAN',
    abbreviation: 'AZE',
  },
  {
    label: 'BURUNDI (BDI)',
    category: 'countries',
    name: 'BURUNDI',
    abbreviation: 'BDI',
  },
  {
    label: 'BELGIUM (BEL)',
    category: 'countries',
    name: 'BELGIUM',
    abbreviation: 'BEL',
  },
  {
    label: 'BENIN (BEN)',
    category: 'countries',
    name: 'BENIN',
    abbreviation: 'BEN',
  },
  {
    label: 'BONAIRE, SINT EUSTATIUS, AND SABA (BES)',
    category: 'countries',
    name: 'BONAIRE, SINT EUSTATIUS, AND SABA',
    abbreviation: 'BES',
  },
  {
    label: 'BURKINA FASO (BFA)',
    category: 'countries',
    name: 'BURKINA FASO',
    abbreviation: 'BFA',
  },
  {
    label: 'BANGLADESH (BGD)',
    category: 'countries',
    name: 'BANGLADESH',
    abbreviation: 'BGD',
  },
  {
    label: 'BULGARIA (BGR)',
    category: 'countries',
    name: 'BULGARIA',
    abbreviation: 'BGR',
  },
  {
    label: 'BAHRAIN (BHR)',
    category: 'countries',
    name: 'BAHRAIN',
    abbreviation: 'BHR',
  },
  {
    label: 'BAHAMAS, THE (BHS)',
    category: 'countries',
    name: 'BAHAMAS, THE',
    abbreviation: 'BHS',
  },
  {
    label: 'BOSNIA AND HERZEGOVINA (BIH)',
    category: 'countries',
    name: 'BOSNIA AND HERZEGOVINA',
    abbreviation: 'BIH',
  },
  {
    label: 'BELARUS (BLR)',
    category: 'countries',
    name: 'BELARUS',
    abbreviation: 'BLR',
  },
  {
    label: 'BELIZE (BLZ)',
    category: 'countries',
    name: 'BELIZE',
    abbreviation: 'BLZ',
  },
  {
    label: 'BERMUDA (BMU)',
    category: 'countries',
    name: 'BERMUDA',
    abbreviation: 'BMU',
  },
  {
    label: 'BOLIVIA (BOL)',
    category: 'countries',
    name: 'BOLIVIA',
    abbreviation: 'BOL',
  },
  {
    label: 'BRAZIL (BRA)',
    category: 'countries',
    name: 'BRAZIL',
    abbreviation: 'BRA',
  },
  {
    label: 'BARBADOS (BRB)',
    category: 'countries',
    name: 'BARBADOS',
    abbreviation: 'BRB',
  },
  {
    label: 'BRUNEI (BRN)',
    category: 'countries',
    name: 'BRUNEI',
    abbreviation: 'BRN',
  },
  {
    label: 'BHUTAN (BTN)',
    category: 'countries',
    name: 'BHUTAN',
    abbreviation: 'BTN',
  },
  {
    label: 'BOTSWANA (BWA)',
    category: 'countries',
    name: 'BOTSWANA',
    abbreviation: 'BWA',
  },
  {
    label: 'CENTRAL AFRICAN REPUBLIC (CAF)',
    category: 'countries',
    name: 'CENTRAL AFRICAN REPUBLIC',
    abbreviation: 'CAF',
  },
  {
    label: 'CANADA (CAN)',
    category: 'countries',
    name: 'CANADA',
    abbreviation: 'CAN',
  },
  {
    label: 'COCOS (KEELING) ISLANDS (CCK)',
    category: 'countries',
    name: 'COCOS (KEELING) ISLANDS',
    abbreviation: 'CCK',
  },
  {
    label: 'SWITZERLAND (CHE)',
    category: 'countries',
    name: 'SWITZERLAND',
    abbreviation: 'CHE',
  },
  {
    label: 'CHILE (CHL)',
    category: 'countries',
    name: 'CHILE',
    abbreviation: 'CHL',
  },
  {
    label: 'CHINA (CHN)',
    category: 'countries',
    name: 'CHINA',
    abbreviation: 'CHN',
  },
  {
    label: "COTE D'IVOIRE (CIV)",
    category: 'countries',
    name: "COTE D'IVOIRE",
    abbreviation: 'CIV',
  },
  {
    label: 'CAMEROON (CMR)',
    category: 'countries',
    name: 'CAMEROON',
    abbreviation: 'CMR',
  },
  {
    label: 'DEMOCRATIC REPUBLIC OF THE CONGO (COD)',
    category: 'countries',
    name: 'DEMOCRATIC REPUBLIC OF THE CONGO',
    abbreviation: 'COD',
  },
  {
    label: 'REPUBLIC OF THE CONGO (COG)',
    category: 'countries',
    name: 'REPUBLIC OF THE CONGO',
    abbreviation: 'COG',
  },
  {
    label: 'COOK ISLANDS (COK)',
    category: 'countries',
    name: 'COOK ISLANDS',
    abbreviation: 'COK',
  },
  {
    label: 'COLOMBIA (COL)',
    category: 'countries',
    name: 'COLOMBIA',
    abbreviation: 'COL',
  },
  {
    label: 'COMOROS (COM)',
    category: 'countries',
    name: 'COMOROS',
    abbreviation: 'COM',
  },
  {
    label: 'CABO VERDE (CPV)',
    category: 'countries',
    name: 'CABO VERDE',
    abbreviation: 'CPV',
  },
  {
    label: 'COSTA RICA (CRI)',
    category: 'countries',
    name: 'COSTA RICA',
    abbreviation: 'CRI',
  },
  {
    label: 'CUBA (CUB)',
    category: 'countries',
    name: 'CUBA',
    abbreviation: 'CUB',
  },
  {
    label: 'CURACAO (CUW)',
    category: 'countries',
    name: 'CURACAO',
    abbreviation: 'CUW',
  },
  {
    label: 'CAYMAN ISLANDS (CYM)',
    category: 'countries',
    name: 'CAYMAN ISLANDS',
    abbreviation: 'CYM',
  },
  {
    label: 'CYPRUS (CYP)',
    category: 'countries',
    name: 'CYPRUS',
    abbreviation: 'CYP',
  },
  {
    label: 'CZECH REPUBLIC (CZE)',
    category: 'countries',
    name: 'CZECH REPUBLIC',
    abbreviation: 'CZE',
  },
  {
    label: 'DUTCH CARIBBEAN (DCR)',
    category: 'countries',
    name: 'DUTCH CARIBBEAN',
    abbreviation: 'DCR',
  },
  {
    label: 'GERMANY (DEU)',
    category: 'countries',
    name: 'GERMANY',
    abbreviation: 'DEU',
  },
  {
    label: 'DJIBOUTI (DJI)',
    category: 'countries',
    name: 'DJIBOUTI',
    abbreviation: 'DJI',
  },
  {
    label: 'DOMINICA (DMA)',
    category: 'countries',
    name: 'DOMINICA',
    abbreviation: 'DMA',
  },
  {
    label: 'DENMARK (DNK)',
    category: 'countries',
    name: 'DENMARK',
    abbreviation: 'DNK',
  },
  {
    label: 'DOMINICAN REPUBLIC (DOM)',
    category: 'countries',
    name: 'DOMINICAN REPUBLIC',
    abbreviation: 'DOM',
  },
  {
    label: 'ALGERIA (DZA)',
    category: 'countries',
    name: 'ALGERIA',
    abbreviation: 'DZA',
  },
  {
    label: 'ECUADOR (ECU)',
    category: 'countries',
    name: 'ECUADOR',
    abbreviation: 'ECU',
  },
  {
    label: 'EGYPT (EGY)',
    category: 'countries',
    name: 'EGYPT',
    abbreviation: 'EGY',
  },
  {
    label: 'ERITREA (ERI)',
    category: 'countries',
    name: 'ERITREA',
    abbreviation: 'ERI',
  },
  {
    label: 'SPAIN (ESP)',
    category: 'countries',
    name: 'SPAIN',
    abbreviation: 'ESP',
  },
  {
    label: 'ESTONIA (EST)',
    category: 'countries',
    name: 'ESTONIA',
    abbreviation: 'EST',
  },
  {
    label: 'ETHIOPIA (ETH)',
    category: 'countries',
    name: 'ETHIOPIA',
    abbreviation: 'ETH',
  },
  {
    label: 'FINLAND (FIN)',
    category: 'countries',
    name: 'FINLAND',
    abbreviation: 'FIN',
  },
  {
    label: 'FIJI (FJI)',
    category: 'countries',
    name: 'FIJI',
    abbreviation: 'FJI',
  },
  {
    label: 'FALKLAND ISLANDS (ISLAS MALVINAS) (FLK)',
    category: 'countries',
    name: 'FALKLAND ISLANDS (ISLAS MALVINAS)',
    abbreviation: 'FLK',
  },
  {
    label: 'FRANCE (FRA)',
    category: 'countries',
    name: 'FRANCE',
    abbreviation: 'FRA',
  },
  {
    label: 'FAROE ISLANDS (FRO)',
    category: 'countries',
    name: 'FAROE ISLANDS',
    abbreviation: 'FRO',
  },
  {
    label: 'MICRONESIA, FEDERATED STATES OF (FSM)',
    category: 'countries',
    name: 'MICRONESIA, FEDERATED STATES OF',
    abbreviation: 'FSM',
  },
  {
    label: 'GABON (GAB)',
    category: 'countries',
    name: 'GABON',
    abbreviation: 'GAB',
  },
  {
    label: 'UNITED KINGDOM (GBR)',
    category: 'countries',
    name: 'UNITED KINGDOM',
    abbreviation: 'GBR',
  },
  {
    label: 'GEORGIA (GEO)',
    category: 'countries',
    name: 'GEORGIA',
    abbreviation: 'GEO',
  },
  {
    label: 'GHANA (GHA)',
    category: 'countries',
    name: 'GHANA',
    abbreviation: 'GHA',
  },
  {
    label: 'GIBRALTAR (GIB)',
    category: 'countries',
    name: 'GIBRALTAR',
    abbreviation: 'GIB',
  },
  {
    label: 'GUINEA (GIN)',
    category: 'countries',
    name: 'GUINEA',
    abbreviation: 'GIN',
  },
  {
    label: 'GUADELOUPE (GLP)',
    category: 'countries',
    name: 'GUADELOUPE',
    abbreviation: 'GLP',
  },
  {
    label: 'GAMBIA, THE (GMB)',
    category: 'countries',
    name: 'GAMBIA, THE',
    abbreviation: 'GMB',
  },
  {
    label: 'GUINEA-BISSAU (GNB)',
    category: 'countries',
    name: 'GUINEA-BISSAU',
    abbreviation: 'GNB',
  },
  {
    label: 'EQUATORIAL GUINEA (GNQ)',
    category: 'countries',
    name: 'EQUATORIAL GUINEA',
    abbreviation: 'GNQ',
  },
  {
    label: 'GREECE (GRC)',
    category: 'countries',
    name: 'GREECE',
    abbreviation: 'GRC',
  },
  {
    label: 'GRENADA (GRD)',
    category: 'countries',
    name: 'GRENADA',
    abbreviation: 'GRD',
  },
  {
    label: 'GREENLAND (GRL)',
    category: 'countries',
    name: 'GREENLAND',
    abbreviation: 'GRL',
  },
  {
    label: 'GUATEMALA (GTM)',
    category: 'countries',
    name: 'GUATEMALA',
    abbreviation: 'GTM',
  },
  {
    label: 'GUAM (GU)',
    category: 'countries',
    name: 'GUAM',
    abbreviation: 'GU',
  },
  {
    label: 'FRENCH GUIANA (GUF)',
    category: 'countries',
    name: 'FRENCH GUIANA',
    abbreviation: 'GUF',
  },
  {
    label: 'GUYANA (GUY)',
    category: 'countries',
    name: 'GUYANA',
    abbreviation: 'GUY',
  },
  {
    label: 'HAWAII (HI)',
    category: 'countries',
    name: 'HAWAII',
    abbreviation: 'HI',
  },
  {
    label: 'HONG KONG (HKG)',
    category: 'countries',
    name: 'HONG KONG',
    abbreviation: 'HKG',
  },
  {
    label: 'HONDURAS (HND)',
    category: 'countries',
    name: 'HONDURAS',
    abbreviation: 'HND',
  },
  {
    label: 'CROATIA (HRV)',
    category: 'countries',
    name: 'CROATIA',
    abbreviation: 'HRV',
  },
  {
    label: 'HAITI (HTI)',
    category: 'countries',
    name: 'HAITI',
    abbreviation: 'HTI',
  },
  {
    label: 'HUNGARY (HUN)',
    category: 'countries',
    name: 'HUNGARY',
    abbreviation: 'HUN',
  },
  {
    label: 'INDONESIA (IDN)',
    category: 'countries',
    name: 'INDONESIA',
    abbreviation: 'IDN',
  },
  {
    label: 'INDIA (IND)',
    category: 'countries',
    name: 'INDIA',
    abbreviation: 'IND',
  },
  {
    label: 'CHAGOS ARCHIPELAGO (IOT)',
    category: 'countries',
    name: 'CHAGOS ARCHIPELAGO',
    abbreviation: 'IOT',
  },
  {
    label: 'IRELAND (IRL)',
    category: 'countries',
    name: 'IRELAND',
    abbreviation: 'IRL',
  },
  {
    label: 'IRAN (IRN)',
    category: 'countries',
    name: 'IRAN',
    abbreviation: 'IRN',
  },
  {
    label: 'IRAQ (IRQ)',
    category: 'countries',
    name: 'IRAQ',
    abbreviation: 'IRQ',
  },
  {
    label: 'ICELAND (ISL)',
    category: 'countries',
    name: 'ICELAND',
    abbreviation: 'ISL',
  },
  {
    label: 'ISRAEL (ISR)',
    category: 'countries',
    name: 'ISRAEL',
    abbreviation: 'ISR',
  },
  {
    label: 'ITALY (ITA)',
    category: 'countries',
    name: 'ITALY',
    abbreviation: 'ITA',
  },
  {
    label: 'JAMAICA (JAM)',
    category: 'countries',
    name: 'JAMAICA',
    abbreviation: 'JAM',
  },
  {
    label: 'JORDAN (JOR)',
    category: 'countries',
    name: 'JORDAN',
    abbreviation: 'JOR',
  },
  {
    label: 'JAPAN (JPN)',
    category: 'countries',
    name: 'JAPAN',
    abbreviation: 'JPN',
  },
  {
    label: 'KAZAKHSTAN (KAZ)',
    category: 'countries',
    name: 'KAZAKHSTAN',
    abbreviation: 'KAZ',
  },
  {
    label: 'KENYA (KEN)',
    category: 'countries',
    name: 'KENYA',
    abbreviation: 'KEN',
  },
  {
    label: 'KYRGYZSTAN (KGZ)',
    category: 'countries',
    name: 'KYRGYZSTAN',
    abbreviation: 'KGZ',
  },
  {
    label: 'CAMBODIA (KHM)',
    category: 'countries',
    name: 'CAMBODIA',
    abbreviation: 'KHM',
  },
  {
    label: 'KIRIBATI (KIR)',
    category: 'countries',
    name: 'KIRIBATI',
    abbreviation: 'KIR',
  },
  {
    label: 'SAINT KITTS AND NEVIS (KNA)',
    category: 'countries',
    name: 'SAINT KITTS AND NEVIS',
    abbreviation: 'KNA',
  },
  {
    label: 'KOREA, SOUTH (KOR)',
    category: 'countries',
    name: 'KOREA, SOUTH',
    abbreviation: 'KOR',
  },
  {
    label: 'KUWAIT (KWT)',
    category: 'countries',
    name: 'KUWAIT',
    abbreviation: 'KWT',
  },
  {
    label: 'LAOS (LAO)',
    category: 'countries',
    name: 'LAOS',
    abbreviation: 'LAO',
  },
  {
    label: 'LEBANON (LBN)',
    category: 'countries',
    name: 'LEBANON',
    abbreviation: 'LBN',
  },
  {
    label: 'LIBERIA (LBR)',
    category: 'countries',
    name: 'LIBERIA',
    abbreviation: 'LBR',
  },
  {
    label: 'LIBYA (LBY)',
    category: 'countries',
    name: 'LIBYA',
    abbreviation: 'LBY',
  },
  {
    label: 'ST LUCIA (LCA)',
    category: 'countries',
    name: 'ST LUCIA',
    abbreviation: 'LCA',
  },
  {
    label: 'LIECHTENSTEIN (LIE)',
    category: 'countries',
    name: 'LIECHTENSTEIN',
    abbreviation: 'LIE',
  },
  {
    label: 'SRI LANKA (LKA)',
    category: 'countries',
    name: 'SRI LANKA',
    abbreviation: 'LKA',
  },
  {
    label: 'LESOTHO (LSO)',
    category: 'countries',
    name: 'LESOTHO',
    abbreviation: 'LSO',
  },
  {
    label: 'LITHUANIA (LTU)',
    category: 'countries',
    name: 'LITHUANIA',
    abbreviation: 'LTU',
  },
  {
    label: 'LUXEMBOURG (LUX)',
    category: 'countries',
    name: 'LUXEMBOURG',
    abbreviation: 'LUX',
  },
  {
    label: 'LATVIA (LVA)',
    category: 'countries',
    name: 'LATVIA',
    abbreviation: 'LVA',
  },
  {
    label: 'MACAU (MAC)',
    category: 'countries',
    name: 'MACAU',
    abbreviation: 'MAC',
  },
  {
    label: 'MOROCCO (MAR)',
    category: 'countries',
    name: 'MOROCCO',
    abbreviation: 'MAR',
  },
  {
    label: 'MONACO (MCO)',
    category: 'countries',
    name: 'MONACO',
    abbreviation: 'MCO',
  },
  {
    label: 'MOLDOVA (MDA)',
    category: 'countries',
    name: 'MOLDOVA',
    abbreviation: 'MDA',
  },
  {
    label: 'MADAGASCAR (MDG)',
    category: 'countries',
    name: 'MADAGASCAR',
    abbreviation: 'MDG',
  },
  {
    label: 'MALDIVES (MDV)',
    category: 'countries',
    name: 'MALDIVES',
    abbreviation: 'MDV',
  },
  {
    label: 'MEXICO (MEX)',
    category: 'countries',
    name: 'MEXICO',
    abbreviation: 'MEX',
  },
  {
    label: 'MARSHALL ISLANDS (MHL)',
    category: 'countries',
    name: 'MARSHALL ISLANDS',
    abbreviation: 'MHL',
  },
  {
    label: 'NORTH MACEDONIA (MKD)',
    category: 'countries',
    name: 'NORTH MACEDONIA',
    abbreviation: 'MKD',
  },
  {
    label: 'MALI (MLI)',
    category: 'countries',
    name: 'MALI',
    abbreviation: 'MLI',
  },
  {
    label: 'MALTA (MLT)',
    category: 'countries',
    name: 'MALTA',
    abbreviation: 'MLT',
  },
  {
    label: 'BURMA (MMR)',
    category: 'countries',
    name: 'BURMA',
    abbreviation: 'MMR',
  },
  {
    label: 'MONTENEGRO (MNE)',
    category: 'countries',
    name: 'MONTENEGRO',
    abbreviation: 'MNE',
  },
  {
    label: 'MONGOLIA (MNG)',
    category: 'countries',
    name: 'MONGOLIA',
    abbreviation: 'MNG',
  },
  {
    label: 'MOZAMBIQUE (MOZ)',
    category: 'countries',
    name: 'MOZAMBIQUE',
    abbreviation: 'MOZ',
  },
  {
    label: 'NORTHERN MARIANA ISLANDS (MP)',
    category: 'countries',
    name: 'NORTHERN MARIANA ISLANDS',
    abbreviation: 'MP',
  },
  {
    label: 'MAURITANIA (MRT)',
    category: 'countries',
    name: 'MAURITANIA',
    abbreviation: 'MRT',
  },
  {
    label: 'MONTSERRAT (MSR)',
    category: 'countries',
    name: 'MONTSERRAT',
    abbreviation: 'MSR',
  },
  {
    label: 'MARTINIQUE (MTQ)',
    category: 'countries',
    name: 'MARTINIQUE',
    abbreviation: 'MTQ',
  },
  {
    label: 'MAURITIUS (MUS)',
    category: 'countries',
    name: 'MAURITIUS',
    abbreviation: 'MUS',
  },
  {
    label: 'MALAWI (MWI)',
    category: 'countries',
    name: 'MALAWI',
    abbreviation: 'MWI',
  },
  {
    label: 'MALAYSIA (MYS)',
    category: 'countries',
    name: 'MALAYSIA',
    abbreviation: 'MYS',
  },
  {
    label: 'MAYOTTE (MYT)',
    category: 'countries',
    name: 'MAYOTTE',
    abbreviation: 'MYT',
  },
  {
    label: 'NAMIBIA (NAM)',
    category: 'countries',
    name: 'NAMIBIA',
    abbreviation: 'NAM',
  },
  {
    label: 'NEW CALEDONIA (NCL)',
    category: 'countries',
    name: 'NEW CALEDONIA',
    abbreviation: 'NCL',
  },
  {
    label: 'NIGER (NER)',
    category: 'countries',
    name: 'NIGER',
    abbreviation: 'NER',
  },
  {
    label: 'NIGERIA (NGA)',
    category: 'countries',
    name: 'NIGERIA',
    abbreviation: 'NGA',
  },
  {
    label: 'NICARAGUA (NIC)',
    category: 'countries',
    name: 'NICARAGUA',
    abbreviation: 'NIC',
  },
  {
    label: 'NIUE (NIU)',
    category: 'countries',
    name: 'NIUE',
    abbreviation: 'NIU',
  },
  {
    label: 'NETHERLANDS (NLD)',
    category: 'countries',
    name: 'NETHERLANDS',
    abbreviation: 'NLD',
  },
  {
    label: 'NORWAY (NOR)',
    category: 'countries',
    name: 'NORWAY',
    abbreviation: 'NOR',
  },
  {
    label: 'NEPAL (NPL)',
    category: 'countries',
    name: 'NEPAL',
    abbreviation: 'NPL',
  },
  {
    label: 'NAURU (NRU)',
    category: 'countries',
    name: 'NAURU',
    abbreviation: 'NRU',
  },
  {
    label: 'NEW ZEALAND (NZL)',
    category: 'countries',
    name: 'NEW ZEALAND',
    abbreviation: 'NZL',
  },
  {
    label: 'OMAN (OMN)',
    category: 'countries',
    name: 'OMAN',
    abbreviation: 'OMN',
  },
  {
    label: 'OTHER FOREIGN LOCALITIES (OTH)',
    category: 'countries',
    name: 'OTHER FOREIGN LOCALITIES',
    abbreviation: 'OTH',
  },
  {
    label: 'PAKISTAN (PAK)',
    category: 'countries',
    name: 'PAKISTAN',
    abbreviation: 'PAK',
  },
  {
    label: 'PANAMA (PAN)',
    category: 'countries',
    name: 'PANAMA',
    abbreviation: 'PAN',
  },
  {
    label: 'PERU (PER)',
    category: 'countries',
    name: 'PERU',
    abbreviation: 'PER',
  },
  {
    label: 'PHILIPPINES (PHL)',
    category: 'countries',
    name: 'PHILIPPINES',
    abbreviation: 'PHL',
  },
  {
    label: 'PALAU (PLW)',
    category: 'countries',
    name: 'PALAU',
    abbreviation: 'PLW',
  },
  {
    label: 'PAPUA NEW GUINEA (PNG)',
    category: 'countries',
    name: 'PAPUA NEW GUINEA',
    abbreviation: 'PNG',
  },
  {
    label: 'POLAND (POL)',
    category: 'countries',
    name: 'POLAND',
    abbreviation: 'POL',
  },
  {
    label: 'PUERTO RICO (PR)',
    category: 'countries',
    name: 'PUERTO RICO',
    abbreviation: 'PR',
  },
  {
    label: "DEM. PEOPLE'S REPUBLIC OF KOREA (PRK)",
    category: 'countries',
    name: "DEM. PEOPLE'S REPUBLIC OF KOREA",
    abbreviation: 'PRK',
  },
  {
    label: 'PORTUGAL (PRT)',
    category: 'countries',
    name: 'PORTUGAL',
    abbreviation: 'PRT',
  },
  {
    label: 'PARAGUAY (PRY)',
    category: 'countries',
    name: 'PARAGUAY',
    abbreviation: 'PRY',
  },
  {
    label: 'FRENCH POLYNESIA (PYF)',
    category: 'countries',
    name: 'FRENCH POLYNESIA',
    abbreviation: 'PYF',
  },
  {
    label: 'QATAR (QAT)',
    category: 'countries',
    name: 'QATAR',
    abbreviation: 'QAT',
  },
  {
    label: 'MIDWAY ISLANDS (QM)',
    category: 'countries',
    name: 'MIDWAY ISLANDS',
    abbreviation: 'QM',
  },
  {
    label: 'WAKE ISLAND (QW)',
    category: 'countries',
    name: 'WAKE ISLAND',
    abbreviation: 'QW',
  },
  {
    label: 'RESERVE COMPONENT (RES)',
    category: 'countries',
    name: 'RESERVE COMPONENT',
    abbreviation: 'RES',
  },
  {
    label: 'REUNION (REU)',
    category: 'countries',
    name: 'REUNION',
    abbreviation: 'REU',
  },
  {
    label: 'ROMANIA (ROU)',
    category: 'countries',
    name: 'ROMANIA',
    abbreviation: 'ROU',
  },
  {
    label: 'RUSSIA (RUS)',
    category: 'countries',
    name: 'RUSSIA',
    abbreviation: 'RUS',
  },
  {
    label: 'RWANDA (RWA)',
    category: 'countries',
    name: 'RWANDA',
    abbreviation: 'RWA',
  },
  {
    label: 'SAUDI ARABIA (SAU)',
    category: 'countries',
    name: 'SAUDI ARABIA',
    abbreviation: 'SAU',
  },
  {
    label: 'SUDAN (SDN)',
    category: 'countries',
    name: 'SUDAN',
    abbreviation: 'SDN',
  },
  {
    label: 'SENEGAL (SEN)',
    category: 'countries',
    name: 'SENEGAL',
    abbreviation: 'SEN',
  },
  {
    label: 'SINGAPORE (SGP)',
    category: 'countries',
    name: 'SINGAPORE',
    abbreviation: 'SGP',
  },
  {
    label: 'SAINT HELENA (SHN)',
    category: 'countries',
    name: 'SAINT HELENA',
    abbreviation: 'SHN',
  },
  {
    label: 'SOLOMON ISLANDS (SLB)',
    category: 'countries',
    name: 'SOLOMON ISLANDS',
    abbreviation: 'SLB',
  },
  {
    label: 'SIERRA LEONE (SLE)',
    category: 'countries',
    name: 'SIERRA LEONE',
    abbreviation: 'SLE',
  },
  {
    label: 'EL SALVADOR (SLV)',
    category: 'countries',
    name: 'EL SALVADOR',
    abbreviation: 'SLV',
  },
  {
    label: 'SAN MARINO (SMR)',
    category: 'countries',
    name: 'SAN MARINO',
    abbreviation: 'SMR',
  },
  {
    label: 'SOMALIA (SOM)',
    category: 'countries',
    name: 'SOMALIA',
    abbreviation: 'SOM',
  },
  {
    label: 'SERBIA (SRB)',
    category: 'countries',
    name: 'SERBIA',
    abbreviation: 'SRB',
  },
  {
    label: 'SOUTH SUDAN (SSD)',
    category: 'countries',
    name: 'SOUTH SUDAN',
    abbreviation: 'SSD',
  },
  {
    label: 'SAO TOME AND PRINCIPE (STP)',
    category: 'countries',
    name: 'SAO TOME AND PRINCIPE',
    abbreviation: 'STP',
  },
  {
    label: 'SURINAME (SUR)',
    category: 'countries',
    name: 'SURINAME',
    abbreviation: 'SUR',
  },
  {
    label: 'SLOVAKIA (SVK)',
    category: 'countries',
    name: 'SLOVAKIA',
    abbreviation: 'SVK',
  },
  {
    label: 'SLOVENIA (SVN)',
    category: 'countries',
    name: 'SLOVENIA',
    abbreviation: 'SVN',
  },
  {
    label: 'SWEDEN (SWE)',
    category: 'countries',
    name: 'SWEDEN',
    abbreviation: 'SWE',
  },
  {
    label: 'ESWATINI (SWZ)',
    category: 'countries',
    name: 'ESWATINI',
    abbreviation: 'SWZ',
  },
  {
    label: 'SINT MAARTEN (SXM)',
    category: 'countries',
    name: 'SINT MAARTEN',
    abbreviation: 'SXM',
  },
  {
    label: 'SEYCHELLES (SYC)',
    category: 'countries',
    name: 'SEYCHELLES',
    abbreviation: 'SYC',
  },
  {
    label: 'SYRIA (SYR)',
    category: 'countries',
    name: 'SYRIA',
    abbreviation: 'SYR',
  },
  {
    label: 'TURKS AND CAICOS ISLANDS (TCA)',
    category: 'countries',
    name: 'TURKS AND CAICOS ISLANDS',
    abbreviation: 'TCA',
  },
  {
    label: 'CHAD (TCD)',
    category: 'countries',
    name: 'CHAD',
    abbreviation: 'TCD',
  },
  {
    label: 'TOGO (TGO)',
    category: 'countries',
    name: 'TOGO',
    abbreviation: 'TGO',
  },
  {
    label: 'THAILAND (THA)',
    category: 'countries',
    name: 'THAILAND',
    abbreviation: 'THA',
  },
  {
    label: 'TAJIKISTAN (TJK)',
    category: 'countries',
    name: 'TAJIKISTAN',
    abbreviation: 'TJK',
  },
  {
    label: 'TOKELAU (TKL)',
    category: 'countries',
    name: 'TOKELAU',
    abbreviation: 'TKL',
  },
  {
    label: 'TURKMENISTAN (TKM)',
    category: 'countries',
    name: 'TURKMENISTAN',
    abbreviation: 'TKM',
  },
  {
    label: 'TIMOR-LESTE (TLS)',
    category: 'countries',
    name: 'TIMOR-LESTE',
    abbreviation: 'TLS',
  },
  {
    label: 'TONGA (TON)',
    category: 'countries',
    name: 'TONGA',
    abbreviation: 'TON',
  },
  {
    label: 'TRINIDAD AND TOBAGO (TTO)',
    category: 'countries',
    name: 'TRINIDAD AND TOBAGO',
    abbreviation: 'TTO',
  },
  {
    label: 'TUNISIA (TUN)',
    category: 'countries',
    name: 'TUNISIA',
    abbreviation: 'TUN',
  },
  {
    label: 'TURKEY (TUR)',
    category: 'countries',
    name: 'TURKEY',
    abbreviation: 'TUR',
  },
  {
    label: 'TUVALU (TUV)',
    category: 'countries',
    name: 'TUVALU',
    abbreviation: 'TUV',
  },
  {
    label: 'TAIWAN (TWN)',
    category: 'countries',
    name: 'TAIWAN',
    abbreviation: 'TWN',
  },
  {
    label: 'TANZANIA (TZA)',
    category: 'countries',
    name: 'TANZANIA',
    abbreviation: 'TZA',
  },
  {
    label: 'UGANDA (UGA)',
    category: 'countries',
    name: 'UGANDA',
    abbreviation: 'UGA',
  },
  {
    label: 'UKRAINE (UKR)',
    category: 'countries',
    name: 'UKRAINE',
    abbreviation: 'UKR',
  },
  {
    label: 'URUGUAY (URY)',
    category: 'countries',
    name: 'URUGUAY',
    abbreviation: 'URY',
  },
  {
    label: 'UZBEKISTAN (UZB)',
    category: 'countries',
    name: 'UZBEKISTAN',
    abbreviation: 'UZB',
  },
  {
    label: 'HOLY SEE (VAT)',
    category: 'countries',
    name: 'HOLY SEE',
    abbreviation: 'VAT',
  },
  {
    label: 'SAINT VINCENT AND THE GRENADINES (VCT)',
    category: 'countries',
    name: 'SAINT VINCENT AND THE GRENADINES',
    abbreviation: 'VCT',
  },
  {
    label: 'VENEZUELA (VEN)',
    category: 'countries',
    name: 'VENEZUELA',
    abbreviation: 'VEN',
  },
  {
    label: 'VIRGIN ISLANDS, BRITISH (VGB)',
    category: 'countries',
    name: 'VIRGIN ISLANDS, BRITISH',
    abbreviation: 'VGB',
  },
  {
    label: 'VIRGIN ISLANDS (U.S.) (VI)',
    category: 'countries',
    name: 'VIRGIN ISLANDS (U.S.)',
    abbreviation: 'VI',
  },
  {
    label: 'VIETNAM (VNM)',
    category: 'countries',
    name: 'VIETNAM',
    abbreviation: 'VNM',
  },
  {
    label: 'VANUATU (VUT)',
    category: 'countries',
    name: 'VANUATU',
    abbreviation: 'VUT',
  },
  {
    label: 'WALLIS AND FUTUNA (WLF)',
    category: 'countries',
    name: 'WALLIS AND FUTUNA',
    abbreviation: 'WLF',
  },
  {
    label: 'SAMOA (WSM)',
    category: 'countries',
    name: 'SAMOA',
    abbreviation: 'WSM',
  },
  {
    label: 'KOSOVO (XKS)',
    category: 'countries',
    name: 'KOSOVO',
    abbreviation: 'XKS',
  },
  {
    label: 'YEMEN (YEM)',
    category: 'countries',
    name: 'YEMEN',
    abbreviation: 'YEM',
  },
  {
    label: 'SOUTH AFRICA (ZAF)',
    category: 'countries',
    name: 'SOUTH AFRICA',
    abbreviation: 'ZAF',
  },
  {
    label: 'ZAMBIA (ZMB)',
    category: 'countries',
    name: 'ZAMBIA',
    abbreviation: 'ZMB',
  },
  {
    label: 'ZIMBABWE (ZWE)',
    category: 'countries',
    name: 'ZIMBABWE',
    abbreviation: 'ZWE',
  },
];
